In [1]:
# Libraries in python
# Python libraries is a collection of functions and methods that allows you to perform many actions without writing your code

In [3]:
# 1. Python NumPy
# NumPy stands for Numerical python and is the core library for numeric and scientific computing
# It consists of multi_dimensional array objects and a collection of routines for processing those arrays

In [5]:
# creating NumPy arrays

In [7]:
# 1. single_dimensional array

In [9]:
import numpy as np

In [23]:
l1 = [1,2,4,5]

In [25]:
n1 = np.array(l1)
n1

array([1, 2, 4, 5])

In [27]:
type(n1)

numpy.ndarray

In [19]:
# 2. multiple_dimensional array

In [39]:
n2 = np.array([[2,34,1],[64,125,5]])
n2

array([[  2,  34,   1],
       [ 64, 125,   5]])

In [41]:
type(n2)

numpy.ndarray

In [133]:
# Initializing NumPy array with zero

In [47]:
n3 = np.zeros((3,5))

In [49]:
n3

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [51]:
type(n3)

numpy.ndarray

In [131]:
# initializing NumPy array with the same number

In [55]:
n4 = np.full((4,4),10)

In [57]:
n4

array([[10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10],
       [10, 10, 10, 10]])

In [129]:
# initializing NumPy array within an range

In [61]:
n5 = np.arange(10,20)

In [63]:
n5

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [65]:
# values in series

In [67]:
n6 = np.arange(10,50,5)

In [69]:
n6

array([10, 15, 20, 25, 30, 35, 40, 45])

In [71]:
# initializing NumPay with random number

In [73]:
n7 = np. random.randint(10,50,6)

In [75]:
n7

array([31, 35, 31, 32, 22, 43])

In [79]:
n8 = np.array([[10,13,232],[214,42,14]])

In [81]:
n8

array([[ 10,  13, 232],
       [214,  42,  14]])

In [83]:
n8.shape

(2, 3)

In [85]:
n8.shape = (3,2)

In [87]:
n8.shape

(3, 2)

In [89]:
n8

array([[ 10,  13],
       [232, 214],
       [ 42,  14]])

In [93]:
# virtical stack

In [95]:
n9 = np.array([12,4,5])
n10 = np.array([53,2,6])

In [97]:
n9,n10

(array([12,  4,  5]), array([53,  2,  6]))

In [101]:
np.vstack((n9,n10))

array([[12,  4,  5],
       [53,  2,  6]])

In [103]:
# horizental stack

In [105]:
np.hstack((n9,n10))

array([12,  4,  5, 53,  2,  6])

In [107]:
# column stack

In [109]:
np.column_stack((n9,n10))

array([[12, 53],
       [ 4,  2],
       [ 5,  6]])

In [121]:
# NumPy intersection

In [123]:
n11 = np.array([12,20,30,40,50,60])
n12 = np.array([50,60,70,80,90])

In [125]:
np.intersect1d(n11,n12)

array([50, 60])

In [135]:
# Numpy Difference

In [137]:
np.setdiff1d(n11,n12)

array([12, 20, 30, 40])

In [139]:
np.setdiff1d(n12,n11)

array([70, 80, 90])

In [153]:
# sum of all

In [141]:
n13=np.array([10,20])
n14=np.array([30,40])

In [143]:
np.sum([n13,n14])

100

In [155]:
# sum of columns attributes

In [145]:
np.sum([n13,n14],axis=0)

array([40, 60])

In [157]:
# sum of rows attributes

In [147]:
np.sum([n13,n14],axis=1)

array([30, 70])

In [151]:
n15=np.array([10,20,30])

In [159]:
# addition
n15=n15+1

In [161]:
n15

array([11, 21, 31])

In [163]:
# subtract
n15=n15-1

In [165]:
n15

array([10, 20, 30])

In [191]:
# multiply
n15=n15*2

In [193]:
n15

array([10., 20., 30.])

In [195]:
# devision
n15=n15/2

In [197]:
n15

array([ 5., 10., 15.])

In [221]:
n16 = np.array([5,20,30,40,50])

In [223]:
# mean
n16 = np.mean(n16)

In [225]:
n16

29.0

In [235]:
# median
n16 = np.array([5,20,30,40,50])
n16 = np.median(n16)

In [237]:
n16

30.0

In [239]:
# standard deviation
n16 = np.array([5,20,30,40,50])
n16 = np.std(n16)

In [241]:
n16

15.620499351813308

In [243]:
# Numpy save and load

In [255]:
n17 = np.array([12,43,15])
np.save('myarray',n17)

In [259]:
n18=np.load('myarray.npy')
n18

array([12, 43, 15])